# Generated by Django 2.2.7 on 2019-11-15 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='asking_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='minimum_increment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='partial_listing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='volume',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='water_type',
            field=models.CharField(max_length=50),
        ),
    ]
