# Generated by Django 2.2.7 on 2019-11-21 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20191115_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('offer_price', models.IntegerField()),
                ('requested_volume', models.IntegerField()),
                ('offering_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='listings.Listing')),
            ],
        ),
    ]
