# Generated by Django 2.2.7 on 2019-11-21 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_offer_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='offering_on',
            new_name='listing',
        ),
    ]
